### ISSUE TITLE
可否考慮下區分匚、匸   艸(艹)、卝呢?

### ISSUE THREAD

**Issue by jisbig5** [Ayaginu-Sue/Astalia#1]
卝:護穫敬警寬舊繭權灌歡....
匚:匯櫃匱...
匸:匹區匿匾....

**Comment by Ayaginu-Sue** [comment]
似乎很有意思，之後時間寬裕的話仔細看看有沒有可行性。
之前有想法修改 艸（艹），但是後來發現工作量有點太大了，所以姑且暫緩了，就留給之後的我痛苦吧……

**Comment by Ayaginu-Sue** [comment]
今天努力了一下，在 Telegram 頻道更新了測試版 [Version 0.051](https://t.me/Mokis_life/662) 的 .ttf 檔，更新日誌是：
- 區分匚、匸
- 大量字形細節修改
也許之後版本的區分匚和匸可以稍微期待一下。

**Comment by Ayaginu-Sue** [comment]
更新了。
